.github/workflows/test.yml

This PR closes #8 with adding GitHub actions workflow to run `rake test`.

Set up GH actions to run tests

---

_includes/footer.html

Source website of the website is fixed. This PR is made for https://github.com/fulldecent/mtssites/issues/4276

rnmobility.com source_website fixed.

---

_includes/trackingcode4.html

This PR is made for https://github.com/fulldecent/mtssites/issues/4335
Anti-flicker snippet is removed. Google Optimize code for GA4 is added.

rnmobility.com trackingcode updated for GA4 google optimize.

---

alabamace.md

Phone number is updated.
This PR is made for https://github.com/fulldecent/mtssites/issues/4875

rnmobility.com phone numbers updated.

---

source/README.md

Invalid front matter is fixed.
This PR is made for https://github.com/fulldecent/mtssites/issues/5632

rnmobility.com invalid front matter is fixed.

---

test/test-build-html-validate.mjs

Let us know what kind of change you would like to see on this page (fix a bug, add content, delete content, edit content)
If you would like us to edit, delete, or add content, please provide us with citations that validate your claim for why we should take such an action. Also, let us know the wording you would like to see.
If you are reporting a bug, please describe the bug and provide screenshots that can help us see what you are describing.
Finally, remember to have a nice day!

error if failing build, for #5382

---

source/_includes/footer.html

This PR is made for https://github.com/fulldecent/mtssites/issues/5123

rnmobility.com replaced jquery with vanilla js es6.

---

.htmlvalidate.json

This PR is made for https://github.com/fulldecent/mtssites/issues/6079

rnmobility.com added the missing html validation config file.

---

source/_includes/trackingcode4.html

This PR is made for https://github.com/fulldecent/mtssites/issues/6440

rnmobility.com removed google optimize from tracking_code as it is gone.

---

source/_includes/ACLSR-schema.html
source/_includes/BLSR-schema.html
source/_includes/PALSR-schema.html
source/_includes/head.html

This PR is made for https://github.com/fulldecent/mtssites/issues/5757

rnmobility.com courses schema added.

---

package.json
yarn.lock

This PR is made for https://github.com/fulldecent/mtssites/issues/6541.
This update was required to smoothly run test in Github actions.

rnmobility.com updated the version of better-sqlite3.

---

package.json
test/test-build-html-validate.mjs
yarn.lock

This PR is made for https://github.com/fulldecent/mtssites/issues/6601

rnmobility.com updated package.json and all related files.

---

source/_includes/footer.html

This PR is made for https://github.com/fulldecent/mtssites/issues/6878

rnmobility.com updated to 2024.

---

source/_includes/footer.html
source/_includes/head.html

Replaced font-awesome with bootstrap-icon.
This PR is made for https://github.com/fulldecent/mtssites/issues/6890.

rnmobility.com bootstrap icon's CDN is updated.

---

test/plugin.html-validate.internal-links.mjs

This PR is made for https://github.com/fulldecent/mtssites/issues/6992

rnmobility.com updated internal links test.

---

_config.yml
source/_includes/head.html
source/aboutrnmobility.html
source/hawaiice.md
source/index.html
source/nursinglicensurecompact.html

This PR is made for https://github.com/fulldecent/mtssites/issues/7083.
Duplicate titles are fixed.

rnmobility.com fixed the duplicate titles in all pages.

---

test/plugin.html-validate.external-links.mjs

This PR is made for https://github.com/fulldecent/mtssites/issues/7126
Test is updated to have less false broken links reported.

rnmobility.com updated external links test for false broken links.

---

source/_includes/ACLSR-schema.html
source/_includes/BLSR-schema.html
source/_includes/PALSR-schema.html

This PR is for https://github.com/fulldecent/mtssites/issues/7206

rnmobility.com updated schema

---

test/fixtures/external-link-broken.html
test/plugin.html-validate.external-links.mjs
test/skip-urls.regex.txt

This PR is made for https://github.com/fulldecent/mtssites/issues/7126.

rnmobility.com adding tests falling.

---

source/_includes/head.html
source/_includes/header.html
source/_layouts/page.html
source/northcarolinace.md
source/northdakotace.md
source/southcarolinace.md
source/texasce.md
source/wyomingce.md

This PR is made for https://github.com/fulldecent/mtssites/issues/7126.

rnmobility.com fixed all pages tests failing.

---

.github/workflows/build-test-deploy.yml
generate-sitemap.js

This PR is made for https://github.com/fulldecent/mtssites/issues/7236

rnmobility.com made changes to automate sitemap.xml generation.

---

source/_includes/footer.html

This PR is made for [#7000](https://github.com/fulldecent/mtssites/issues/7000) and [#7087](https://github.com/fulldecent/mtssites/issues/7087).

rnmobility.com fixed canonical links issue.

---

source/_includes/footer.html

This PR is made for https://github.com/fulldecent/mtssites/issues/7000 and https://github.com/fulldecent/mtssites/issues/7087

rnmobility.com fixed source_website for experiment pages.

---

.github/workflows/build-test-deploy.yml
generate-sitemap.js

This PR is made for https://github.com/fulldecent/mtssites/issues/7236
Experiment pages will not be added to the sitemap.xml now.

rnmobility.com updated generate-sitemap to exclude experiment pages.

---

.vscode/extensions.json
.vscode/settings.json

This PR is made for https://github.com/fulldecent/mtssites/issues/7517.

rnmobility.com updated the formatting.

---

source/index.html

feat: update copy for features section

---

source/_includes/footer.html
source/_layouts/home.html
source/css/index.css
source/index.html

@fulldecent it seems the changes made to the copy in the earlier PR were overridden. This PR fixes that, as well as makes the grid containing the state cards 4 columns on desktop screens and redesigns the footer section

feat: redo copy & redesign footer section

---

source/_includes/compact-state.html
source/_includes/footer.html
source/_includes/public-feedback.html
source/_layouts/other.html
source/_layouts/page.html
source/aboutrnmobility.html
source/css/index.css
source/nursinglicensurecompact.html

feat: redesign state content page

---

source/_includes/mailto.html
source/alaskace.md

feat: fix awesome mail issues

---

source/_includes/footer.html
source/css/index.css

This PR is for #71 
- Added new footer

rnmobility.com New footer

---

source/_includes/head.html
source/_includes/navbar.html
source/_layouts/home.html
source/css/index.css

This PR is for #71 
- Added new header

rnmobility.com New header

---

source/_includes/footer.html
source/_includes/mailto.html
source/_includes/navbar.html

@fulldecent I'm not sure if this would trigger the bare URL markdown error but the emails weren't being added properly to the mail to url
This PR also addresses some of the external redirect errors showing up on CI

feat: fix mailto address & external redirect errors

---

.prettierrc.js
README.md
_config.yml
package.json
test/skip-urls.regex.txt
test/yaml-validate.mjs
yarn.lock

Contributes to https://github.com/modern-training-solutions/public-websites/issues/8185

sync gh pages template

---

source/_includes/footer.html

rnmobility.com moved to Shopify shopping cart.

---

test/build-html-validate.mjs
test/fixtures-html-validate-should-fail.mjs
test/fixtures/image-missing-alt.html
test/plugin.html-validate.internal-links.mjs

Contributes to https://github.com/modern-training-solutions/public-websites/issues/8434

add check for img alt attribute
